language: java
jdk:
  - oraclejdk7

'before-install:
 - sudo apt-get 7zip
 - sudo wget http://www.java2s.com/Code/JarDownload/javax/javax.persistence.jar.zip ~
 - sudo 7zip e ~/javax.*.zip

deps-jar: ~/javax.*.jar
