language: java
jdk:
  - oraclejdk7

before_script:
  - mysql -e 'create database prosub;'

before_install:
 - sudo apt-get update
 - sudo apt-get install libeclipselink-java
 - sudo apt-get install glassfish-*
 - sudo apt-get install netbeans
 - sudo apt-get install mysql-server mysql-client
 - sudo apt-get install openjdk-7-jre
 - sudo tree netbeans*/java/modules/ext/eclipselink/
